name: code coverage

on:
  push:
    branches:
      - '**'
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: enable corepack
        run: corepack enable
      - name: use node LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: install code climate reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /tmp/cc-test-reporter
          chmod +x /tmp/cc-test-reporter
          /tmp/cc-test-reporter before-build
      - name: install dependencies
        run: pnpm install
      - name: run coverage
        run: pnpm run coverage
        env:
          CI: true
      - name: upload coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: /tmp/cc-test-reporter after-build --exit-code $? || [ ! -s coverage/lcov.info ]
