name: release

on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: enable corepack
        run: corepack enable
      - name: use node LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: install dependencies
        run: pnpm install
      - name: create release notes
        run: npx gh-release@7 --yes
        env:
          GH_RELEASE_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: login to npm
        run: pnpm config set //registry.npmjs.org/:_authToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: release to npm
        run: pnpm publish --no-git-checks
        env:
          NPM_CONFIG_PROVENANCE: true
