name: code test

on:
  push:
    branches:
      - '**'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18, 19, 20, 21]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: use node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: install dependencies
        run: npm ci
      - name: run test
        run: npm test
        env:
          CI: true
      - name: run build
        run: npm run build --if-present
